name: 개발서버 Redis 배포

on:
  pull_request:
    branches:
      - "develop"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: EC2 연결 및 Redis 이미지 실행
        uses: appleboy/ssh-action@master 
        with:
          username: ubuntu
          host: ${{ secrets.HOST_DEV }}
          key: ${{ secrets.KEY }}
          script: |
            sudo docker stop redis-dev
            sudo docker rm redis-dev
            sudo docker rmi redis:7.0
            sudo docker pull redis:7.0
            sudo docker run -d \
                --name redis-dev \
                --network backend \
                -e TZ=Asia/Seoul \
                -p 6379:6379 \
                redis:7.0
